<?php
startHeader();
setTitle($title);
includeStyle('bootstrap.css');
includeStyle('icons.css');
includeStyle('login.css');
includeStyle('stylesheet.css');
includeStyle('stylesheets.css');
includeStyle('pagination.css');
includeScript('jquery-2.1.3.min.js');
includeScript('checkBox.js');
endHeader();